### ISSUE TITLE
涉及链表的题目，代码提交之后编译无法通过，而官网可以正常提交

### ISSUE THREAD

**Issue by IamCaine** [ccagml/leetcode_extension#173]
使用的Java语言
ListNode 我在本地创建了这个类型，但是代码编写页面依然报错。同样提交上去编译也无法通过。

**Comment by ccagml** [comment]
@IamCaine 可以给个例子吗?
一般ListNode是官网内置自带的,不需要自己写
你的代码,可以直接在leetcode.cn网页上提交吗

**Comment by IamCaine** [comment]
是我的问题 写的有问题 不好意思
